import torch


def mse(output, target):
    '''
    :param output: Result generated by neural network
    :param target: Ground truth
    :return: Mean squared error between
    '''
    return torch.pow(output-target, 2).mean().float()




