# Configuration file description:
# Interpolation method comes from Step2 of:
# Two-Stage Self-supervised Cycle-Consistency Network for Reconstruction of Thin-Slice MR Images


device: 'cuda:0'                 # 'cpu' when cuda not available, else 'cuda:0'
model_config:
  model_name: 'IKC'          # Name of the model
  checkpoint_path: null         # Path to load from saved checkpoints. Enter 'null' when train from scratch
dataset_config:
  loader_name: 'dataset_mydatabase_IKC'      # Name of the dataset loader

  # Below are self-defined parameters used by 'cifar10'
  #dataset_path: 'E:\20211209Skin'
  dataset_path: '/home/yxsun/win_data/20211209Skin'
  train_batch_size: 8
  val_batch_size: 8
train_config:
  strategy_name: 'TrainIKC'   # Strategy for training

  # Below are self-defined parameters used by 'regular'
  max_epoch: 1000              # Maximum epoch
  print_freq: 5             # Print log every several iterations
  learning_rate: 0.00001         # Learning rate


